disallowed-methods = [
    { path = "std::process::Command::new", reason = "Use `ctx.execute()` or `ctx.execute().always()`" },
    { path = "std::process::Command::output", reason = "Use `output_checked[_with][_utf8]`" },
    { path = "std::process::Command::spawn", reason = "Use `spawn_checked`" },
    { path = "std::process::Command::status", reason = "Use `status_checked`" },
]
