name: Check config file creation if not exists

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always


permissions:
  contents: read

jobs:
  TestConfig:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      - run: |
          CONFIG_PATH=~/.config/topgrade.toml;
          if [ -f "$CONFIG_PATH" ]; then rm $CONFIG_PATH; fi
          cargo build; 
          TOPGRADE_SKIP_BRKC_NOTIFY=true ./target/debug/topgrade --run-mode dry --only system;
          stat $CONFIG_PATH;
