on:
  pull_request:
  push:
    branches:
      - main

name: Check i18n

permissions:
  contents: read

jobs:
  check_locale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Install checker
        # Build it with the dev profile as this is faster and the checker still works
        run: |
          cargo install --git https://github.com/topgrade-rs/topgrade_i18n_locale_checker --profile dev

      - name: Run the checker
        run: topgrade_i18n_locale_checker --locale-file ./locales/app.yml --rust-src-to-check ./src
